#' Compare tibbles of required packages and existing packages
#'
#' Compare the package and name package versions of the two tibbles. Add a
#' new column "server_status", specifying if package exists and needs upgrading,
#' does not exist, so needs to be acquired, or exists at the right version.
#'
#' @param required_packages Tibble of required packages.
#' generated by get_required_packages()
#' @param server_packages Tibble of server packages.
#' generated by existing_server_packages()
#'
#' @return Tibble with status of each required package.
#' @export
#'
#' @examples
#' \dontrun{
#' available_long_tb <- available_packages_long()
#' required_tb <- search_requirements(available_long_tb, "fabletools")
#' server_tb <- existing_server_packages("my_server/R_Packages/R_3_6_3_Packages")
#' compare_tb <- compare_available_server(required_tb, server_tb)
#' }
compare_available_server <- function(required_packages, server_packages) {
  # Join required and available by package name then compare versions
  required_packages %>%
    dplyr::left_join(server_packages, by = c("package" = "server_package")) %>%
    dplyr::mutate(
      min_package_version
      = stringr::str_extract(.data$package_version_required, "\\(([^)]+)\\)")
    ) %>%
    # get brackets version
    dplyr::mutate(
      min_package_version =
        stringr::str_extract(.data$min_package_version, "[0-9\\.]+")
    ) %>%
    # get version number inside bracket
    dplyr::mutate(server_status = dplyr::case_when(
      is.na(.data$min_package_version)
      & !is.na(.data$server_version) ~ "server version currently OK",
      is.na(.data$server_version) ~ "package not currently on server",
      numeric_version(.data$server_version, strict = FALSE) <
        numeric_version(.data$min_package_version, strict = FALSE)
      ~ "server version need upgrading",
      numeric_version(.data$server_version, strict = FALSE) >=
        numeric_version(.data$min_package_version, strict = FALSE)
      ~ "server version currently OK"
    ))
}
